# \uC2A4\uD504\uB9C1 \uC560\uD50C\uB9AC\uCF00\uC774\uC158 \uC774\uB984
spring.application.name=springboot

# H2 \uB370\uC774\uD130\uBCA0\uC774\uC2A4 \uC124\uC815 (\uBA54\uBAA8\uB9AC \uBAA8\uB4DC)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate \uC124\uC815
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# \uAE30\uC0C1\uCCAD API \uC124\uC815 (\uC6B0\uB9AC\uAC00 \uCD94\uAC00\uD560 \uAC83)
weather.api.service-key=7c31eb2115c1fd2421b18726edf219f25c5cc2aa073512fec8ed8354ff359a67
weather.api.base-url=https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getUltraSrtFcst